CREATE DATABASE Locadora;

USE Locadora;

CREATE TABLE Empresa
(
	idEmpresa INT PRIMARY KEY IDENTITY NOT NULL
);

CREATE TABLE Veiculo
(
	idVeiculo INT PRIMARY KEY IDENTITY NOT NULL
	, idEmpresa INT FOREIGN KEY REFERENCES Empresa(idEmpresa) NOT NULL
	, Marca VARCHAR(200) NOT NULL
	, Modelo VARCHAR(200) NOT NULL
	, Placa VARCHAR(200) NOT NULL
);

CREATE TABLE Cliente
(
	idCliente INT PRIMARY KEY IDENTITY NOT NULL
	, Nome VARCHAR(200) NOT NULL
	, Numero_de_Identidade VARCHAR(200) NOT NULL
	, CPF VARCHAR(200) NOT NULL
);

CREATE TABLE Aluguel
(
	idAluguel INT PRIMARY KEY IDENTITY NOT NULL
	, idVeiculo	INT FOREIGN KEY REFERENCES Veiculo(idVeiculo) NOT NULL
	, idCliente INT FOREIGN KEY REFERENCES Cliente(idCliente) NOT NULL
	, Preço SMALLMONEY NOT NULL
	, Data DATETIME NOT NULL
);