CREATE DATABASE pclinics;

USE pclinics;

CREATE TABLE Clinica
(
	idClinica INT PRIMARY KEY IDENTITY NOT NULL
	, Endereço VARCHAR(200) NOT NULL
);

CREATE TABLE Veterinario
(
	idVeterinario INT PRIMARY KEY IDENTITY NOT NULL
	, idClinica INT FOREIGN KEY REFERENCES Clinica(idClinica) NOT NULL
	, Nome VARCHAR(200) NOT NULL
);

CREATE TABLE Pet
(
	idPet INT PRIMARY KEY IDENTITY NOT NULL
	, Nome VARCHAR(200) NOT NULL
	, Data_de_Nascimento DATE NOT NULL
	, Tipo_de_Pet VARCHAR(50) NOT NULL
	, Raça VARCHAR(50) NOT NULL
	, Dono VARCHAR(200) NOT NULL 
);

CREATE TABLE Consulta
(
	idConsulta INT PRIMARY KEY IDENTITY NOT NULL
	, idVeterinario INT FOREIGN KEY REFERENCES Veterinario(idVeterinario) NOT NULL
	, idPet INT FOREIGN KEY REFERENCES Pet(idPet) NOT NULL
	, Data DATETIME NOT NULL
);